// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.7.0.0
//      SpecFlow Generator Version:3.7.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace patronage21_qa_appium.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.7.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RegistrationPage")]
    public partial class RegistrationPageFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "RegistrationPage.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "RegistrationPage", "\tNew user wants to be able to register an account\r\n\tto apply for the Patronative " +
                    "program", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
 testRunner.Given("User is on Registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("REGISTRATION_PAGE_1_IP2-261_registration_page_displayed_correctly")]
        public virtual void REGISTRATION_PAGE_1_IP2_261_Registration_Page_Displayed_Correctly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("REGISTRATION_PAGE_1_IP2-261_registration_page_displayed_correctly", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 11
 testRunner.Then("User sees Registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("REGISTRATION_PAGE_2_IP2-261_registration_is_possible_after_filling_in_the_form_co" +
            "rrectly")]
        public virtual void REGISTRATION_PAGE_2_IP2_261_Registration_Is_Possible_After_Filling_In_The_Form_Correctly()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("REGISTRATION_PAGE_2_IP2-261_registration_is_possible_after_filling_in_the_form_co" +
                    "rrectly", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 15
 testRunner.When("User completes \"form\" \"correctly\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
 testRunner.Then("User \"can\" sign up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
 testRunner.And("User sees \"Email verification\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("REGISTRATION_PAGE_3_IP2-261_registration_form_has_proper_validation")]
        [NUnit.Framework.TestCaseAttribute("name", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("name", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("name", "too short", null)]
        [NUnit.Framework.TestCaseAttribute("name", "too long", null)]
        [NUnit.Framework.TestCaseAttribute("name", "with digit", null)]
        [NUnit.Framework.TestCaseAttribute("name", "with special character", null)]
        [NUnit.Framework.TestCaseAttribute("surname", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("surname", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("surname", "too short", null)]
        [NUnit.Framework.TestCaseAttribute("surname", "too long", null)]
        [NUnit.Framework.TestCaseAttribute("surname", "with digit", null)]
        [NUnit.Framework.TestCaseAttribute("surname", "with special character", null)]
        [NUnit.Framework.TestCaseAttribute("email", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("email", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("email", "with no @", null)]
        [NUnit.Framework.TestCaseAttribute("email", "with no sign before @", null)]
        [NUnit.Framework.TestCaseAttribute("email", "with no . after @", null)]
        [NUnit.Framework.TestCaseAttribute("email", "with no sign before . after @", null)]
        [NUnit.Framework.TestCaseAttribute("email", "with no sign after . after @", null)]
        [NUnit.Framework.TestCaseAttribute("phone", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("phone", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("phone", "too short", null)]
        [NUnit.Framework.TestCaseAttribute("phone", "too long", null)]
        [NUnit.Framework.TestCaseAttribute("phone", "with letter", null)]
        [NUnit.Framework.TestCaseAttribute("technologies", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("technologies", "with too few selections", null)]
        [NUnit.Framework.TestCaseAttribute("technologies", "with to many selections", null)]
        [NUnit.Framework.TestCaseAttribute("login", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("login", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("login", "too short", null)]
        [NUnit.Framework.TestCaseAttribute("login", "too long", null)]
        [NUnit.Framework.TestCaseAttribute("login", "with special character", null)]
        [NUnit.Framework.TestCaseAttribute("password", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("password", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("password", "too short", null)]
        [NUnit.Framework.TestCaseAttribute("password", "too long", null)]
        [NUnit.Framework.TestCaseAttribute("password", "with no uppercase letter", null)]
        [NUnit.Framework.TestCaseAttribute("password", "with no digit", null)]
        [NUnit.Framework.TestCaseAttribute("password", "with no special character", null)]
        [NUnit.Framework.TestCaseAttribute("confirm password", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("confirm password", "with wrong password", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with no http", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with no www", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with no github.com", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with no username", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with too long username", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with non-alphanumeric character in username", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with hyphen at start in username", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with hyphen at end in username", null)]
        [NUnit.Framework.TestCaseAttribute("consent", "correctly", null)]
        [NUnit.Framework.TestCaseAttribute("consent", "by leave required", null)]
        public virtual void REGISTRATION_PAGE_3_IP2_261_Registration_Form_Has_Proper_Validation(string data, string inAWay, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("data", data);
            argumentsOfScenario.Add("in a way", inAWay);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("REGISTRATION_PAGE_3_IP2-261_registration_form_has_proper_validation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 21
 testRunner.When(string.Format("User completes \"{0}\" \"{1}\"", data, inAWay), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.Then(string.Format("User is informed about validation result of entered \"{0}\"", data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("REGISTRATION_PAGE_4_IP2-261_registration_is_not_possible_after_filling_in_the_for" +
            "m_incorrectly")]
        [NUnit.Framework.TestCaseAttribute("name", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("surname", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("email", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("phone", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("technologies", "with too few selections", null)]
        [NUnit.Framework.TestCaseAttribute("login", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("password", "with no data", null)]
        [NUnit.Framework.TestCaseAttribute("confirm password", "with wrong password", null)]
        [NUnit.Framework.TestCaseAttribute("Github", "with no http", null)]
        [NUnit.Framework.TestCaseAttribute("consent", "by leave required", null)]
        public virtual void REGISTRATION_PAGE_4_IP2_261_Registration_Is_Not_Possible_After_Filling_In_The_Form_Incorrectly(string data, string incorrectly, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("data", data);
            argumentsOfScenario.Add("incorrectly", incorrectly);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("REGISTRATION_PAGE_4_IP2-261_registration_is_not_possible_after_filling_in_the_for" +
                    "m_incorrectly", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 80
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 81
 testRunner.When("User completes \"form\" \"correctly\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 82
 testRunner.And(string.Format("User completes \"{0}\" \"{1}\"", data, incorrectly), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 83
 testRunner.Then("User \"can not\" sign up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("REGISTRATION_PAGE_5_IP2-261_registration_is_not_possible_with_email_which_was_use" +
            "d_before")]
        public virtual void REGISTRATION_PAGE_5_IP2_261_Registration_Is_Not_Possible_With_Email_Which_Was_Used_Before()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("REGISTRATION_PAGE_5_IP2-261_registration_is_not_possible_with_email_which_was_use" +
                    "d_before", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 100
 testRunner.When("User signs up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 101
 testRunner.And("User signs up again with the same email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 102
 testRunner.Then("User \"can not\" sign up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
